### ISSUE TITLE
Write down design of lexer/parser

### ISSUE THREAD

**Issue by abtv** [abtv/ice#9]

**Comment by ACEof** [comment]
First we need to define the minimum syntax of the language.

**Comment by abtv** [comment]
You can write it down. Just look on `UI example` and `Goals for the language`. It should be possible to implement `UI example` and it's enough at the moment. Then we will add more features, but not now. @ACEof

**Comment by abtv** [comment]
Please write parser design here before implementation. I hope it will save us a lot of time.
